### ISSUE TITLE
搭建从库遇到的问题

### ISSUE THREAD

**Issue by 364137920** [Tencent/phxsql#117]
hi，你好，我目前遇到如下问题

新增的从库，在启动phxbinlogsvr_phxrpc后报错

```
mysql> show slave status\G
*************************** 1. row ***************************
               Slave_IO_State: 
                  Master_Host: 127.0.0.1
                  Master_User: replica
                  Master_Port: 6000
                Connect_Retry: 60
              Master_Log_File: 
          Read_Master_Log_Pos: 4
               Relay_Log_File: relay-log.000039
                Relay_Log_Pos: 893356263
        Relay_Master_Log_File: 
             Slave_IO_Running: No
            Slave_SQL_Running: No
              Replicate_Do_DB: 
          Replicate_Ignore_DB: 
           Replicate_Do_Table: 
       Replicate_Ignore_Table: 
      Replicate_Wild_Do_Table: 
  Replicate_Wild_Ignore_Table: 
                   Last_Errno: 1872
                   Last_Error: Slave failed to initialize relay log info structure from the repository
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 0
              Relay_Log_Space: 0
              Until_Condition: None
               Until_Log_File: 
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File: 
           Master_SSL_CA_Path: 
              Master_SSL_Cert: 
            Master_SSL_Cipher: 
               Master_SSL_Key: 
        Seconds_Behind_Master: NULL
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error: 
               Last_SQL_Errno: 1872
               Last_SQL_Error: Slave failed to initialize relay log info structure from the repository
  Replicate_Ignore_Server_Ids: 
             Master_Server_Id: 0
                  Master_UUID: 4bfff3ca.a1cf.22e7.ab89.357e9737b684
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: 
           Master_Retry_Count: 86400
                  Master_Bind: 
      Last_IO_Error_Timestamp: 
     Last_SQL_Error_Timestamp: 170505 13:01:17
               Master_SSL_Crl: 
           Master_SSL_Crlpath: 
           Retrieved_Gtid_Set: 
            Executed_Gtid_Set: 4bfff2ca-a0cf-11e6-ab78-246e9626b573:1-123071618,
54bfafc7-a0cf-11e6-ab78-70e284103994:1-65969570,
58f5fe05-0ea4-11e7-b7ab-246e962a6cc7:1-52642073,
59254800-a0cf-11e6-ab79-70e2841125c0:1-59771186
```

报错的原因是，这个新从库，想要寻找relay-log.000039这个中继日志，然而自己并没有这个中继日志，自己只有如下的中继日志，毕竟是新搭建的嘛
```
-rw-rw---- 1 mysql mysql 143 May  5 11:54 relay-log.000001
-rw-rw---- 1 mysql mysql 143 May  5 12:54 relay-log.000002
-rw-rw---- 1 mysql mysql 143 May  5 12:57 relay-log.000003
-rw-rw---- 1 mysql mysql 195 May  5 12:57 relay-log.index
```

新从库的数据，是从另外一个从库mysqldump导出导入的，发现那个从库的中继日志，刚好就是relay-log.000039，我想问的问题是，为什么这个新从库，会使用别人的中继日志位置点，而不是自己新的为止点呢？
.
另外一个问题，我能否通过先把这个新从库从集群中踢出去，然后再加入进来，接着再重启phxbinlogsvr_phxrpc模块，来达到重新设置同步的信息呢？  我担心的是，按我理解，在集群中，master就会给slave发送binlog数据，一旦踢出集群，master就不会给新从库发送binlog数据，那重新加进来以后，这个时间段缺失的数据会追回来的吗？

后来我把这个从库踢出集群，对立面的mysql进行reset slave 清除错误的位置信息，接着又重启binlogsrv和mysql, , 这个时候，mysql的show slave status没有报错了，但是binlogsrv却报错找不到GTID位置点了

.003463 84631 phx_glog.cpp:78]  GetGTIDIndex get gtid 4bfff2ca-a0cf-11e6-ab78-246e9626b573:123071618, not exist 
E0505 15:32:47.003962 84631 phx_glog.cpp:78]  GetGTIDIndex get gtid 54bfafc7-a0cf-11e6-ab78-70e284103994:65969570, not exist 
E0505 15:32:47.004752 84631 phx_glog.cpp:78]  GetGTIDIndex get gtid 59254800-a0cf-11e6-ab79-70e2841125c0:59771186, not exist 
E0505 15:32:47.107765 84627 phx_glog.cpp:78] STATUS(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 226186899 checkpoint instanceid 226927197 now instanceid 226932912

万分感谢，能否联系qq 364137920呢？
